{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gitlab-ci-pipelines-exporter.fullname" . }}
  labels: {{- include "gitlab-ci-pipelines-exporter.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "gitlab-ci-pipelines-exporter.annotations" . | nindent 4 }}
  {{- end }}
{{- end }}
