{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "gitlab-ci-pipelines-exporter.fullname" . }}
  labels: {{- include "gitlab-ci-pipelines-exporter.labels" . | nindent 4 }}
  {{- if or .Values.ingress.annotations .Values.commonAnnotations }}
  annotations:
    {{- include "gitlab-ci-pipelines-exporter.annotations" . | nindent 4 }}
    {{- if .Values.ingress.annotations }}
    {{- .Values.ingress.annotations | toYaml | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hostname }}
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.path | clean }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "gitlab-ci-pipelines-exporter.fullname" . }}
                port:
                  name: http
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- if and .Values.ingress.tls }}
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      secretName: {{ printf "%s-tls" .Values.ingress.hostname | trunc 63 | trimSuffix "-" }}
    {{- end }}
  {{- end }}
{{- end }}
