apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab-ci-pipelines-exporter.fullname" . }}-secret-token
  labels: {{- include "gitlab-ci-pipelines-exporter.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "gitlab-ci-pipelines-exporter.annotations" . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  token: {{ .Values.gcpe.webhookSecret | b64enc | quote }}
