---
name: Lint (Golang)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/lint.golang.yml
      - go.*
      - cmd/**
      - pkg/**

jobs:
  golangci-lint:
    name: Golang CI lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # tag=v3.5.0
        with:
          go-version: '1.19'
          check-latest: true
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - uses: golangci/golangci-lint-action@0ad9a0988b3973e851ab0a07adf248ec2e100376 # tag=v3.3.1
