---
name: Lint (YAML)
on:  # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
#    paths: ["chart/**"]

jobs:
  yamllint:
    name: YAML lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - uses: ibiqlik/action-yamllint@v3
        with:
          format: github
