---
name: Lint (Github Actions workflows)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths: [.github/workflows/**]

jobs:
  # CI harden security tries to keep your github actions secure by following these simple rules:
  # - Check if no issues are found on your Github Action
  # - Ensure that all action and reusable workflow are pinned using directly a commit SHA
  ci_harden_security:
    name: Github Action security hardening
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Lint your Github Actions
        run: |
          curl -O https://raw.githubusercontent.com/rhysd/actionlint/main/.github/actionlint-matcher.json
          echo "::add-matcher::.github/actionlint-matcher.json"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@bd2868d14a756969608c618665394415a238de69 # v2.0.5
