---
name: Lint (Container)
on:  # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
#    paths: ["chart/**"]

jobs:
  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile
