---
name: Renovate post-script (Helm)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [labeled]
    paths:
      - .github/workflows/renovate.helm.yml
      - charts/**

jobs:
  # Bump automatically the Helm chart when Renovate make an update
  auto_bump:
    name: Auto-bump Helm chart
    runs-on: ubuntu-latest
    if: "contains(github.event.pull_request.labels, 'renovate:need-helm-bump') && github.event.commits[0].message != 'chore: bump Helm version'"
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: mikefarah/yq@87cba2ecbeaecf860efcceb66deab46ae030ce1e # tag=v4.30.6
        with:
          cmd: yq --inplace '.version |= (. | split "." | .[2] |= (. tag="!!int" | . + 1) | join ".")' charts/gitlab-ci-runner-exporter/Chart.yaml
      - uses: EndBug/add-and-commit@61a88be553afe4206585b31aa72387c64295d08b # tag=v9.1.1
        with:
          commit: --signoff
          message: "chore: bump Helm version"
