---
name: Security (Container)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
#    paths: ["chart/**"]

jobs:
  # Analyze statically Helm charts to identify any policy violations.
  checkov:
    name: Checkov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: bridgecrewio/checkov-action@master
        with:
          framework: dockerfile
          skip_check: CKV_DOCKER_2
      - uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          category: checkov-helm
          sarif_file: results.sarif
