---
name: Security (Container)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/security.container.yml
      - Dockerfile

jobs:
  # Analyze statically Helm charts to identify any policy violations.
  checkov:
    name: Checkov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - uses: actions/setup-python@5ccb29d8773c3f3f653e1705f474dfaa8a06a912 # tag=v4.4.0
        with:
          python-version: '3.8'
          check-latest: true

      - uses: bridgecrewio/checkov-action@38a019027b5fef17f476dff522c947229b771ed8
        with:
          framework: dockerfile
          skip_check: CKV_DOCKER_2
      - uses: github/codeql-action/upload-sarif@579411fb6c2fa885902ffeb0238873661aa2dc29 # tag=codeql-bundle-20221211
        if: always()
        with:
          category: checkov-helm
          sarif_file: results.sarif
