---
name: Test (Golang)
on:  # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]

jobs:
  go-test:
    name: Golang test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: Run golang tests
        run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: golang-coverage-report
          path: coverage.out
          retention-days: 1

  codecov:
    name: Codecov
    runs-on: ubuntu-latest
    needs: [go-test]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: golang-coverage-report
      - uses: codecov/codecov-action@v3
